importScripts(
  "./shared/runtime.js",
  "./background/storage.js",
  "./background/downloads.js",
  "./background/tabs.js",
  "./background/debugger.js",
  "./background/injection.js",
  "./background/daemon-client.js",
  "./background/socket-client.js",
  "./background/handlers.js",
  "./background/service-worker.js",
);
