import type { ComponentType } from "react";
import type { AgentPickerComponentItem } from "@agent-picker/workspace/types";
import CardsWelcomeCard from "../../components/agent-picker/drafts/cards/WelcomeCard";

// Generated by scripts/generate-agent-picker-drafts.mjs. Do not edit manually.
export const generatedAgentPickerDraftItems: AgentPickerComponentItem[] = [
  {
    id: "draft-cards-welcomecard",
    title: "Welcome Card",
    shortLabel: "Welcome Card",
    sourceKind: "draft",
    category: "cards",
    componentPath: "components/agent-picker/drafts/cards/WelcomeCard.tsx",
    tags: ["cards","welcome","card"],
    recommendedViewport: "original",
    renderKind: "component",
    Component: CardsWelcomeCard as unknown as ComponentType<Record<string, unknown>>,
    props: {},
  },
];
